name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14 x64 with cached Maven dependencies
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
          architecture: x64
          cache: maven
      - name: Maven verify
        run: mvn --batch-mode --update-snapshots verify
      - name: Prepare artifacts for upload
        run: mkdir staging && cp target/*.jar staging
      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging